apiVersion: v1
kind: Service
metadata:
  name: mysqlpod-0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mysql-set-0
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
